### ISSUE TITLE
Interfacing the HSL

### ISSUE THREAD

**Issue by dpo** [JuliaSmoothOptimizers/HSL.jl#132]
Below is the full list of HSL packages from https://www.hsl.rl.ac.uk/catalogue.

This issue is used to track the progress on HSL interfaces and to assign a priority to each.
Next to each package, please indicate:

* a link to the pull request where the interface is implemented;
* a priority level: 🥇 = high, 🥈 = medium, 🥉 = low.

As a guideline:
* functionality that is already available in pure Julia should have low priority;
* functionality that is already available via an interface to another low-level library should have low or medium priority.

Tick the box when an interface is complete and the pull request has been merged.

We will proceed in stages.

* Stage 1:
    - [ ] Packages with a C interface :trophy:

* Stage 2:
    - [ ] MA Section
    - [ ] MC Section

* Next stages: TBD

<hr>

# EIGENVALUES AND EIGENVECTORS

## EA: Eigenvalues and eigenvectors of real symmetric matrices

- [ ] [EA16](https://www.hsl.rl.ac.uk/catalogue/ea16.html) Compute selected eigenpairs using rational Lanczos method
- [ ] [HSL_EA19](https://www.hsl.rl.ac.uk/catalogue/hsl_ea19.html) Sparse symmetric or Hermitian: leftmost eigenpairs
- [ ] [HSL_EA20](https://www.hsl.rl.ac.uk/catalogue/hsl_ea20.html) s-root of a sparse self-adjoint positive-definite pencil
- [ ] [EA22](https://www.hsl.rl.ac.uk/catalogue/ea22.html) Sparse symmetric: simultaneous iteration
- [ ] [EA25](https://www.hsl.rl.ac.uk/catalogue/ea25.html) Sparse symmetric: Lanczos for the spectrum

## EB: Eigenvalues and eigenvectors of general matrices

- [ ] [EB13](https://www.hsl.rl.ac.uk/catalogue/eb13.html) Sparse unsymmetric: Arnoldi’s method
- [ ] [EB22](https://www.hsl.rl.ac.uk/catalogue/eb22.html) Sparse unsymmetric: subspace iteration

## EP: Parallel eigenvalues and eigenvectors of real symmetric matrices

- [ ] [EP25](https://www.hsl.rl.ac.uk/catalogue/ep25.html) Sparse symmetric: Lanczos for the spectrum

# MATHEMATICAL FUNCTIONS

## FA: Random numbers

- [ ] [FA14](https://www.hsl.rl.ac.uk/catalogue/fa14.html) Uniform distribution
- [ ] [HSL_FA14](https://www.hsl.rl.ac.uk/catalogue/hsl_fa14.html) Uniform distribution

## FD: Simple Functions

- [ ] [FD15](https://www.hsl.rl.ac.uk/catalogue/fd15.html) Real-valued machine constants

# SORTING

## KB: Sorting numbers

- [ ] [KB05](https://www.hsl.rl.ac.uk/catalogue/kb05.html) Sort numbers into ascending order using Quicksort
- [ ] [KB06](https://www.hsl.rl.ac.uk/catalogue/kb06.html) Sort numbers into descending order using Quicksort
- [x] [KB07](https://www.hsl.rl.ac.uk/catalogue/kb07.html) Sort numbers into ascending order with indexing using Quicksort
- [ ] [KB08](https://www.hsl.rl.ac.uk/catalogue/kb08.html) Sort numbers into descending order with indexing using Quicksort
- [ ] [HSL_KB22](https://www.hsl.rl.ac.uk/catalogue/hsl_kb22.html) Sorting reals using the Heapsort method

# LINEAR PROGRAMMING

## LA: Linear prgramming, i.e. minimization of a linear function subject to linear constraints

- [ ] [LA04](https://www.hsl.rl.ac.uk/catalogue/la04.html) Sparse linear programming: steepest-edge simplex method
- [ ] [LA15](https://www.hsl.rl.ac.uk/catalogue/la15.html) Sparse mathematical programming bases: factorize and update

# LINEAR ALGEBRA

## MA: Solution of linear systems

- [ ] [MA38](https://www.hsl.rl.ac.uk/catalogue/ma38.html) Sparse unsymmetric system: unsymmetric multifrontal method
- [ ] [MA41](https://www.hsl.rl.ac.uk/catalogue/ma41.html) Sparse unsymmetric system: unsymmetric multifrontal method
- [ ] [MA42](https://www.hsl.rl.ac.uk/catalogue/ma42.html) Sparse unsymmetric system: out-of-core frontal method
- [ ] [HSL_MA42_ELEMENT](https://www.hsl.rl.ac.uk/catalogue/hsl_ma42_element.html) Unsymmetric finite-element system: out-of-core frontal method (real and complex)
- [ ] [HSL_MA42](https://www.hsl.rl.ac.uk/catalogue/hsl_ma42.html) Sparse unsymmetric system: out-of-core frontal method
- [ ] [MA43](https://www.hsl.rl.ac.uk/catalogue/ma43.html) Sparse unsymmetric system: row-by-row frontal method
- [ ] [MA44](https://www.hsl.rl.ac.uk/catalogue/ma44.html) Over-determined linear system: least-squares solution
- [ ] [MA46](https://www.hsl.rl.ac.uk/catalogue/ma46.html) Sparse unsymmetric finite-element system: multifrontal
- [ ] [MA48](https://www.hsl.rl.ac.uk/catalogue/ma48.html) Sparse unsymmetric system: driver for conventional direct method
- [ ] [HSL_MA48](https://www.hsl.rl.ac.uk/catalogue/hsl_ma48.html) Sparse unsymmetric system: driver for conventional direct  method :trophy: 🥈 
- [ ] [MA49](https://www.hsl.rl.ac.uk/catalogue/ma49.html) Sparse over-determined system: least squares by QR
- [ ] [MA50](https://www.hsl.rl.ac.uk/catalogue/ma50.html) Sparse unsymmetric system: conventional direct method
- [ ] [MA51](https://www.hsl.rl.ac.uk/catalogue/ma51.html) Auxiliary for MA48 and MA50: identify ignored rows or columns in the rectangular or rank-deficient case, compute determinant
- [ ] [MA52](https://www.hsl.rl.ac.uk/catalogue/ma52.html) Sparse unsymmetric finite-element system: out-of-core multiple front method
- [ ] [HSL_MA54](https://www.hsl.rl.ac.uk/catalogue/hsl_ma54.html) Definite symmetric full matrix: partial or complete factorization and solution
- [ ] [HSL_MA55](https://www.hsl.rl.ac.uk/catalogue/hsl_ma55.html) Band symmetric positive-definite system
- [ ] [MA57](https://www.hsl.rl.ac.uk/catalogue/ma57.html) Sparse symmetric system: multifrontal method
- [ ] [HSL_MA57](https://www.hsl.rl.ac.uk/catalogue/hsl_ma57.html) Sparse symmetric system: multifrontal method :trophy: 🥉 
- [ ] [MA60](https://www.hsl.rl.ac.uk/catalogue/ma60.html) Iterative refinement and error estimation
- [ ] [MA61](https://www.hsl.rl.ac.uk/catalogue/ma61.html) Sparse symmetric positive-definite system: incomplete factorization
- [ ] [MA62](https://www.hsl.rl.ac.uk/catalogue/ma62.html) Sparse symmetric finite-element system: out-of-core frontal method
- [ ] [HSL_MA64](https://www.hsl.rl.ac.uk/catalogue/hsl_ma64.html) Indefinite symmetric full matrix: partial or complete factorization and solution
- [ ] [MA65](https://www.hsl.rl.ac.uk/catalogue/ma65.html) Unsymmetric banded system of linear equations
- [ ] [MA67](https://www.hsl.rl.ac.uk/catalogue/ma67.html) Sparse symmetric system, zeros on diagonal: blocked conventional
- [ ] [MA69](https://www.hsl.rl.ac.uk/catalogue/ma69.html) Unsymmetric system whose leading subsystem is easy to solve
- [ ] [HSL_MA69](https://www.hsl.rl.ac.uk/catalogue/hsl_ma69.html) Unsymmetric system whose leading subsystem is easy to solve
- [ ] [MA72](https://www.hsl.rl.ac.uk/catalogue/ma72.html) Sparse symmetric finite-element system: out-of-core multiple front method
- [ ] [HSL_MA74](https://www.hsl.rl.ac.uk/catalogue/hsl_ma74.html) Unsymmetric full matrix: partial or complete factorization and solution
- [ ] [MA75](https://www.hsl.rl.ac.uk/catalogue/ma75.html) Sparse over-determined system: weighted least squares
- [ ] [HSL_MA77](https://www.hsl.rl.ac.uk/catalogue/hsl_ma77.html) Sparse symmetric system: multifrontal out of core :trophy: 🥇 
- [ ] [HSL_MA78](https://www.hsl.rl.ac.uk/catalogue/hsl_ma78.html) Sparse unsymmetric finite-element system: multifrontal out of core
- [ ] [HSL_MA79](https://www.hsl.rl.ac.uk/catalogue/hsl_ma79.html) Sparse symmetric system: mixed precision
- [ ] [HSL_MA85](https://www.hsl.rl.ac.uk/catalogue/hsl_ma85.html) Sparse diagonally-weighted linear least squares solver
- [ ] [HSL_MA86](https://www.hsl.rl.ac.uk/catalogue/hsl_ma86.html) Sparse solver for real and complex indefinite matrices using OpenMP :trophy: 🥇 
- [ ] [HSL_MA87](https://www.hsl.rl.ac.uk/catalogue/hsl_ma87.html) Sparse Cholesky solver for real/complex matrices using OpenMP :trophy: 🥇 
- [ ] [HSL_MA97](https://www.hsl.rl.ac.uk/catalogue/hsl_ma97.html) Bit-compatible parallel sparse symmetric/Hermitian solver using OpenMP :trophy: 🥉 

## MC: Computations with real matrices and vectors

- [ ] [MC13](https://www.hsl.rl.ac.uk/catalogue/mc13.html) Permute a sparse matrix to block triangular form
- [x] [MC21](https://www.hsl.rl.ac.uk/catalogue/mc21.html) Permute a sparse matrix to put entries on the diagonal
- [ ] [MC22](https://www.hsl.rl.ac.uk/catalogue/mc22.html) Permute a sparse matrix given row and column permutations
- [ ] [MC25](https://www.hsl.rl.ac.uk/catalogue/mc25.html) Permute a sparse matrix to block triangular form
- [ ] [MC26](https://www.hsl.rl.ac.uk/catalogue/mc26.html) Sparse rectangular matrix: compute normal matrix
- [ ] [MC29](https://www.hsl.rl.ac.uk/catalogue/mc29.html) Sparse unsymmetric matrix: calculate scaling factors
- [ ] [MC30](https://www.hsl.rl.ac.uk/catalogue/mc30.html) Sparse symmetric matrix: calculate scaling factors
- [ ] [MC33](https://www.hsl.rl.ac.uk/catalogue/mc33.html) Sparse unsymmetric matrix: permute to bordered block triangular form
- [ ] [MC34](https://www.hsl.rl.ac.uk/catalogue/mc34.html) Sparse symmetric structure: expand from lower triangle
- [ ] [HSL_MC34](https://www.hsl.rl.ac.uk/catalogue/hsl_mc34.html) Sparse symmetric structure: expand from lower triangle
- [ ] [MC37](https://www.hsl.rl.ac.uk/catalogue/mc37.html) Sparse symmetric matrix: represent as a sum of element matrices
- [ ] [MC38](https://www.hsl.rl.ac.uk/catalogue/mc38.html) Sparse rectangular matrix held by columns: transpose
- [ ] [MC44](https://www.hsl.rl.ac.uk/catalogue/mc44.html) Unassembled finite-element matrix: generate the element or supervariable connectivity graph
- [ ] [MC46](https://www.hsl.rl.ac.uk/catalogue/mc46.html) Sparse rectangular matrix held by rows: transpose
- [ ] [MC47](https://www.hsl.rl.ac.uk/catalogue/mc47.html) Sparse symmetric pattern: approximate minimum-degree ordering allowing dense rows
- [ ] [MC53](https://www.hsl.rl.ac.uk/catalogue/mc53.html) Generate an ordering for finite-element matrices within a subdomain
- [ ] [MC54](https://www.hsl.rl.ac.uk/catalogue/mc54.html) Write a sparse matrix in Rutherford-Boeing format
- [ ] [MC55](https://www.hsl.rl.ac.uk/catalogue/mc55.html) Write a supplementary file in Rutherford-Boeing format
- [ ] [MC56](https://www.hsl.rl.ac.uk/catalogue/mc56.html) Read a file or a supplementary file held in Rutherford-Boeing format
- [ ] [HSL_MC56](https://www.hsl.rl.ac.uk/catalogue/hsl_mc56.html) Read a file containing a sparse matrix held in format
- [ ] [MC57](https://www.hsl.rl.ac.uk/catalogue/mc57.html) Assemble a set of finite-element matrices
- [ ] [MC58](https://www.hsl.rl.ac.uk/catalogue/mc58.html) Estimate rank and find independent rows/columns of a sparse unsymmetric or rectangular matrix
- [ ] [MC59](https://www.hsl.rl.ac.uk/catalogue/mc59.html) Sort a sparse matrix to an ordering by columns
- [ ] [MC60](https://www.hsl.rl.ac.uk/catalogue/mc60.html) Sparse symmetric pattern: reduce the profile and wavefront
- [ ] [MC61](https://www.hsl.rl.ac.uk/catalogue/mc61.html) Straightforward interface to MC60
- [ ] [MC62](https://www.hsl.rl.ac.uk/catalogue/mc62.html) Generate a row ordering for a row-by-row frontal solver
- [ ] [MC63](https://www.hsl.rl.ac.uk/catalogue/mc63.html) Generate an element assembly ordering for a frontal solver
- [ ] [MC64](https://www.hsl.rl.ac.uk/catalogue/mc64.html) Permute and scale a sparse unsymmetric matrix to put large entries on the diagonal
- [ ] [HSL_MC64](https://www.hsl.rl.ac.uk/catalogue/hsl_mc64.html) Permute and scale a sparse unsymmetric or rectangular matrix to put large entries on the diagonal :trophy: 🥇 
- [ ] [HSL_MC65](https://www.hsl.rl.ac.uk/catalogue/hsl_mc65.html) Construct and manipulate matrices in compressed sparse row format
- [ ] [HSL_MC66](https://www.hsl.rl.ac.uk/catalogue/hsl_mc66.html) Permute an unsymmetric sparse matrix to singly bordered blocked diagonal form
- [ ] [MC67](https://www.hsl.rl.ac.uk/catalogue/mc67.html) Refine a profile-reducing permutation of a symmetric matrix
- [ ] [HSL_MC68](https://www.hsl.rl.ac.uk/catalogue/hsl_mc68.html) Symmetric sparse matrix: compute elimination orderings :trophy: 🥉 
- [ ] [HSL_MC69](https://www.hsl.rl.ac.uk/catalogue/hsl_mc69.html) Matrix format converter :trophy: 🥉 
- [ ] [MC71](https://www.hsl.rl.ac.uk/catalogue/mc71.html) Unsymmetric matrix: estimate 1-norm
- [ ] [MC72](https://www.hsl.rl.ac.uk/catalogue/mc72.html) Full unsymmetric matrix: calculate scaling factors
- [ ] [HSL_MC73](https://www.hsl.rl.ac.uk/catalogue/hsl_mc73.html) Sparse symmetric matrix: compute Fiedler vector and permute to reduce the profile and wavefront
- [ ] [MC75](https://www.hsl.rl.ac.uk/catalogue/mc75.html) Sparse unsymmetric matrix: estimate condition number
- [x] [MC77](https://www.hsl.rl.ac.uk/catalogue/mc77.html) Sparse unsymmetric matrix: calculate scaling factors
- [ ] [HSL_MC78](https://www.hsl.rl.ac.uk/catalogue/hsl_mc78.html) Analysis phase in Cholesky algorithm :trophy: 🥉 
- [ ] [HSL_MC79](https://www.hsl.rl.ac.uk/catalogue/hsl_mc79.html) Sparse matrix: maximum matching and Dulmage-Mendelsohn decomposition :trophy: 🥉 
- [ ] [HSL_MC80](https://www.hsl.rl.ac.uk/catalogue/hsl_mc80.html) Sparse symmetric matrix: matching-based ordering and scaling
- [ ] [HSL_MC81](https://www.hsl.rl.ac.uk/catalogue/hsl_mc81.html) Randomized methods for low-rank matrix approximation

## ME: Solution of complex linear systems and other calculations for complex matrices

- [ ] [ME22](https://www.hsl.rl.ac.uk/catalogue/me22.html) Permute a sparse matrix given row and column permutations
- [ ] [ME38](https://www.hsl.rl.ac.uk/catalogue/me38.html) Sparse unsymmetric system: unsymmetric multifrontal method
- [ ] [ME42](https://www.hsl.rl.ac.uk/catalogue/me42.html) Sparse unsymmetric system: out-of-core frontal method
- [ ] [ME43](https://www.hsl.rl.ac.uk/catalogue/me43.html) Sparse unsymmetric system: row-by-row frontal method
- [ ] [ME48](https://www.hsl.rl.ac.uk/catalogue/me48.html) Sparse unsymmetric system: driver for conventional direct method
- [ ] [ME50](https://www.hsl.rl.ac.uk/catalogue/me50.html) Sparse unsymmetric system: conventional direct method
- [ ] [ME57](https://www.hsl.rl.ac.uk/catalogue/me57.html) Sparse Hermitian or complex symmetric: multifrontal method
- [ ] [HSL_ME57](https://www.hsl.rl.ac.uk/catalogue/hsl_me57.html) Sparse solver for complex symmetric or Hermitian linear systems
- [ ] [ME62](https://www.hsl.rl.ac.uk/catalogue/me62.html) Sparse Hermitian or complex symmetric finite-element system: out-of-core frontal method

See also
[HSL_MA86](https://www.hsl.rl.ac.uk/catalogue/hsl_ma86.html) (Parallel sparse symmetric indefinite/Hermitian)
[HSL_MA87](https://www.hsl.rl.ac.uk/catalogue/hsl_ma87.html) (Parallel sparse Cholesky)
[HSL_MA97](https://www.hsl.rl.ac.uk/catalogue/hsl_ma97.html) (Bit-compatible parallel sparse symmetric/Hermitian)

## MF: Computations with complex matrices and vectors

- [ ] [MF29](https://www.hsl.rl.ac.uk/catalogue/mf29.html) Sparse unsymmetric matrix: calculate scaling factors
- [ ] [MF30](https://www.hsl.rl.ac.uk/catalogue/mf30.html) Sparse symmetric matrix: calculate scaling factors
- [ ] [MF64](https://www.hsl.rl.ac.uk/catalogue/mf64.html) Permute and scale a sparse complex unsymmetric matrix to put large entries on the diagonal
- [ ] [MF71](https://www.hsl.rl.ac.uk/catalogue/mf71.html) Unsymmetric matrix: estimate 1-norm

## MI: Iterative methods for sparse matrices

- [ ] [HSL_MI02](https://www.hsl.rl.ac.uk/catalogue/hsl_mi02.html) Symmetric possibly-indefinite system: SYMMBK method
- [ ] [MI11](https://www.hsl.rl.ac.uk/catalogue/mi11.html) Unsymmetric system: incomplete LU factorization
- [ ] [MI12](https://www.hsl.rl.ac.uk/catalogue/mi12.html) Unsymmetric system: approximate-inverse preconditioner
- [ ] [HSL_MI13](https://www.hsl.rl.ac.uk/catalogue/hsl_mi13.html) Preconditioners for saddle-point systems
- [ ] [MI15](https://www.hsl.rl.ac.uk/catalogue/mi15.html) Unsymmetric system: flexible GMRES
- [ ] [HSL_MI20](https://www.hsl.rl.ac.uk/catalogue/hsl_mi20.html) Unsymmetric system: algebraic multigrid preconditioner :trophy: 🥈 
- [ ] [MI21](https://www.hsl.rl.ac.uk/catalogue/mi21.html) Symmetric positive-definite system: conjugate gradient method
- [ ] [MI23](https://www.hsl.rl.ac.uk/catalogue/mi23.html) Unsymmetric system: CGS (conjugate gradient squared) method
- [ ] [MI24](https://www.hsl.rl.ac.uk/catalogue/mi24.html) Unsymmetric system: GMRES (generalized minimal residual) method
- [ ] [MI25](https://www.hsl.rl.ac.uk/catalogue/mi25.html) Unsymmetric system: BiCG (BiConjugate Gradient) method
- [ ] [MI26](https://www.hsl.rl.ac.uk/catalogue/mi26.html) Unsymmetric system: BiCGStab (BiConjugate Gradient Stabilized) method
- [ ] [HSL_MI27](https://www.hsl.rl.ac.uk/catalogue/hsl_mi27.html) Projected preconditioned conjugate gradient method for saddle-point systems
- [ ] [HSL_MI28](https://www.hsl.rl.ac.uk/catalogue/hsl_mi28.html) Symmetric system: incomplete Cholesky factorization
- [ ] [HSL_MI29](https://www.hsl.rl.ac.uk/catalogue/hsl_mi29.html) MPGMRES: an extension of GMRES which allows multiple preconditioners
- [ ] [HSL_MI30](https://www.hsl.rl.ac.uk/catalogue/hsl_mi30.html) Symmetric indefinite saddle-point system: signed incomplete Cholesky factorization
- [ ] [HSL_MI31](https://www.hsl.rl.ac.uk/catalogue/hsl_mi31.html) Symmetric positive-definite system: conjugate gradient method, stopping according to the A-norm of the error
- [ ] [HSL_MI32](https://www.hsl.rl.ac.uk/catalogue/hsl_mi32.html) Symmetric possibly-indefinite system: MINRES method
- [ ] #134

## MP: MPI dependant packages

- [ ] [HSL_MP01](https://www.hsl.rl.ac.uk/catalogue/hsl_mp01.html) MPI constants
- [ ] [HSL_MP42](https://www.hsl.rl.ac.uk/catalogue/hsl_mp42.html) Unsymmetric finite-element system: multiple-front method, element entry
- [ ] [HSL_MP43](https://www.hsl.rl.ac.uk/catalogue/hsl_mp43.html) Sparse unsymmetric system: multiple-front method, equation entry
- [ ] [HSL_MP48](https://www.hsl.rl.ac.uk/catalogue/hsl_mp48.html) Sparse unsymmetric system: parallel direct method
- [ ] [HSL_MP54](https://www.hsl.rl.ac.uk/catalogue/hsl_mp54.html) Parallel Cholesky solver
- [ ] [HSL_MP62](https://www.hsl.rl.ac.uk/catalogue/hsl_mp62.html) Symmetric finite-element system: multiple-front method
- [ ] [HSL_MP82](https://www.hsl.rl.ac.uk/catalogue/hsl_mp82.html) Tall-skinny QR factorization

# NONLINEAR EQUATIONS

## NS: Solution of systems of nonlinear equations in several unknowns

- [ ] [NS23](https://www.hsl.rl.ac.uk/catalogue/ns23.html) Sparse nonlinear over-determined equations: Marquardt method

# INPUT/OUTPUT

## OF: File management

- [ ] [HSL_OF01](https://www.hsl.rl.ac.uk/catalogue/hsl_of01.html) Fortran virtual memory

# POLYNOMIAL AND RATIONAL FUNCTIONS

## PA: Zeros of polynomials

- [ ] [PA16](https://www.hsl.rl.ac.uk/catalogue/pa16.html) Complex coefficients: all roots by the method of Madsen and Reid
- [ ] [PA17](https://www.hsl.rl.ac.uk/catalogue/pa17.html) Real coefficients: all roots by the method of Madsen and Reid

## YM: Generate test programs for chapter M of the library

- [ ] [YM11](https://www.hsl.rl.ac.uk/catalogue/ym11.html) Generate a random sparse matrix

# FORTRAN SYSTEM FACILITES

## ZB: Array allocation

- [ ] [HSL_ZB01](https://www.hsl.rl.ac.uk/catalogue/hsl_zb01.html) Reallocate an array

## ZD: Derived types

- [ ] [HSL_ZD11](https://www.hsl.rl.ac.uk/catalogue/hsl_zd11.html) Derived type for sparse matrix storage schemes

**Comment by amontoison** [comment]
I added a trophy :trophy: for packages with a C interface.

**Comment by dpo** [comment]
Thanks. I added a priority next to them.
